name: Test Publish
on:
  push:
    branches: [main,master]

jobs:
  test-publish-to-gallery:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          CI_NUGET_KEY: ${{ secrets.CI_NUGET_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path . -NuGetApiKey $env:CI_NUGET_KEY -WhatIf -Verbose